### ISSUE TITLE
error building container

### ISSUE THREAD

**Issue by hstern2** [Washington-University/HCPpipelinesDocker#2]
Trying to build a container using this Dockerfile, but getting

<pre>
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/64/4a/b008d1f8a7b9f5206ecf70a53f84e654707e7616a771d84c05151a4713e9/numpy-1.22.3.zip (11.5MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-9Hp1fi/numpy/setup.py", line 59
        raise RuntimeError(f'Cannot parse version {FULLVERSION}')
                                                               ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9Hp1fi/numpy/
You are using pip version 8.1.2, however version 22.0.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c yum install -y epel-release &&  yum install -y python2-pip.noarch openblas-devel &&       pip2 install numpy &&   pip2 install nibabel==2.3.0 --install-option="--prefix=/export/HCP/epd-7.3.2" &&  yum clean packages &&   rm -rf /var/cache/yum/*' returned a non-zero code: 1
</pre>

**Comment by coalsont** [comment]
That sounds like an issue installing numpy (without a specified version) in the given environment (which may be old and out of date).

This isn't our recommended way to run the pipelines, QuNex (https://qunex.yale.edu/) is the container setup we recommend and support.  This repo may already be abandoned.
